# Generated by Django 6.0.4 on 2026-04-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Otro', max_length=10)),
                ('edad', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('nivelUsuario', models.CharField(choices=[('Entrenador', 'Entrenador'), ('Amateur', 'Amateur'), ('Semi-Pro', 'Semipro'), ('Profesional', 'Pro')], default='Amateur', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
