# Generated by Django 6.0.5 on 2026-05-24 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiusuario', '0002_tokensession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Jugador', 'Jugador'), ('Entrenador', 'Entrenador')], default='Jugador', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivelUsuario',
            field=models.CharField(blank=True, choices=[('Amateur', 'Amateur'), ('Semi-Pro', 'Semipro'), ('Profesional', 'Pro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
    ]
