# Generated by Django 6.0.5 on 2026-05-25 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiusuario', '0003_remove_usuario_edad_usuario_entrenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
