# Generated by Django 6.0.5 on 2026-05-29 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('solicitud_amistad', 'Solicitud Amistad'), ('solicitud_entrenador', 'Solicitud Entrenador'), ('solicitud_aceptada', 'Solicitud Aceptada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('partido_agendado', 'Partido Agendado'), ('partido_aceptado', 'Partido Aceptado'), ('partido_rechazado', 'Partido Rechazado'), ('partido_iniciado', 'Partido Iniciado'), ('partido_finalizado', 'Partido Finalizado')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
