# Generated by Django 6.0.5 on 2026-05-24 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_statistics_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchdata',
            name='match_data_creator_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchdata',
            name='match_data_invited_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchpoint',
            name='match_point_game_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchpoint',
            name='match_point_created_at_idx',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='best_of',
            field=models.IntegerField(choices=[(1, 'One'), (3, 'Three'), (5, 'Five')]),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='id_player_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='id_player_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='match_state',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('INICIADO', 'Iniciado'), ('PAUSADO', 'Pausado'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchpoint',
            name='id_player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_2_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
