# Generated by Django 6.0.5 on 2026-05-25 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_rename_player_fields_add_scheduled_entrenador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='id_local_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
