# Generated by Django 6.0.5 on 2026-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_matchdata_id_local_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgame',
            name='guest_is_serving',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
