# Generated by Django 6.0.6 on 2026-06-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_add_guest_is_serving_to_matchgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpoint',
            name='match_point_p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchpoint',
            name='match_point_p2',
            field=models.BooleanField(default=False),
        ),
    ]
